SPECTACULAR_SETTINGS = {
    'TITLE': 'BidZone API',
    'DESCRIPTION': 'API documentation of BidZone',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'Auction', 'description': 'Auction related endpoints'},
        {'name': 'Auction Chat', 'description': 'Auction Chat related endpoints'},
        {'name': 'Auction Question', 'description': 'Auction Question related endpoints'},
        {'name': 'Auction Answer', 'description': 'Auction Answer related endpoints'},
        {'name': 'Bids', 'description': 'Auction bids related endpoints'},
        {'name': 'Collection', 'description': 'Collection related endpoints'},
        {'name': 'Customer', 'description': 'Customer related endpoints'},
        {'name': 'Customer Address', 'description': 'Customer Address related endpoints'},
        {'name': 'Customer Balance', 'description': 'Customer Balance related endpoints'},
        {'name': 'Delivery', 'description': 'Delivery related endpoints'},
        {'name': 'Product', 'description': 'Product related endpoints'},
        {'name': 'Review', 'description': 'Review related endpoints'},
        {'name': 'Transaction', 'description': 'Transaction related endpoints'},
        {'name': 'Wishlist', 'description': 'Wishlist related endpoints'},
    ],
}
