# Generated by Django 5.0.3 on 2024-04-01 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_address_options_alter_auction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.AddField(
            model_name='delivery',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Completed'), ('X', 'Cancelled'), ('S', 'Schedule'), ('D', 'Deleted')], default='A', max_length=1),
        ),
    ]
