# Generated by Django 5.0.3 on 2024-04-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_remove_delivery_product_delivery_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
    ]
