# Generated by Django 5.0.3 on 2024-04-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_wishlistitem_created_at_wishlistitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
