# Generated by Django 5.0.3 on 2024-04-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['province']},
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['auction']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='usercoin',
            options={'ordering': ['user']},
        ),
    ]
