# Generated by Django 5.0.3 on 2024-04-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_review_reviewer_alter_review_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to='auction.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='auction.customer'),
        ),
    ]
