# Generated by Django 5.0.3 on 2024-04-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_review_reviewer_alter_review_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='customer',
        ),
    ]
