# Generated by Django 5.0.4 on 2024-04-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_rename_seller_product_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'permissions': [('cancel_delivery', 'Can cancel delivery')]},
        ),
    ]
