# Generated by Django 5.0.4 on 2024-04-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_collection_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='customer',
        ),
    ]
