# Generated by Django 5.0.4 on 2024-04-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_rename_user_chat_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoin',
            options={'ordering': ['customer']},
        ),
        migrations.RenameField(
            model_name='usercoin',
            old_name='user',
            new_name='customer',
        ),
    ]
