# Generated by Django 5.0.4 on 2024-04-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_alter_usercoin_options_rename_user_usercoin_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='user',
            new_name='customer',
        ),
    ]
