# Generated by Django 5.0.4 on 2024-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_alter_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
