# Generated by Django 5.0.4 on 2024-04-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_bid_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
            preserve_default=False,
        ),
    ]
