# Generated by Django 5.0.4 on 2024-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal',
            field=models.CharField(default=33700, max_length=255),
            preserve_default=False,
        ),
    ]
