# Generated by Django 5.0.4 on 2024-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_address_postal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='municipality',
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
