# Generated by Django 5.0.4 on 2024-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_rename_city_address_municipality_address_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='tole',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
