# Generated by Django 5.0.4 on 2024-05-18 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0024_rename_postal_address_zip_code_address_tole'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to='auction.customer'),
        ),
    ]
