# Generated by Django 5.0.6 on 2024-05-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending'), ('X', 'Cancelled')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
