# Generated by Django 5.0.3 on 2024-04-04 02:12

import auction.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider/images', validators=[auction.validators.validate_file_size])),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
