# Generated by Django 5.0.4 on 2024-04-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_created_at_slider_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
